# Form implementation generated from reading ui file 'MiniCombatGui.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_gameWindow(object):
    def setupUi(self, gameWindow):
        gameWindow.setObjectName("gameWindow")
        gameWindow.resize(800, 600)
        gameWindow.setMinimumSize(QtCore.QSize(800, 600))
        gameWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(parent=gameWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 3, 781, 561))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label.setMinimumSize(QtCore.QSize(0, 150))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 4, 0, 1, 2)
        self.graphicsView = QtWidgets.QGraphicsView(parent=self.gridLayoutWidget)
        self.graphicsView.setMinimumSize(QtCore.QSize(250, 250))
        self.graphicsView.setMaximumSize(QtCore.QSize(250, 250))
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 1, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.graphicsView_2 = QtWidgets.QGraphicsView(parent=self.gridLayoutWidget)
        self.graphicsView_2.setMinimumSize(QtCore.QSize(250, 250))
        self.graphicsView_2.setMaximumSize(QtCore.QSize(250, 250))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.gridLayout.addWidget(self.graphicsView_2, 1, 1, 1, 1, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 0, 1, 2)
        self.progressBar = QtWidgets.QProgressBar(parent=self.gridLayoutWidget)
        self.progressBar.setMinimumSize(QtCore.QSize(0, 30))
        self.progressBar.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 0, 0, 1, 1)
        self.progressBar_2 = QtWidgets.QProgressBar(parent=self.gridLayoutWidget)
        self.progressBar_2.setMinimumSize(QtCore.QSize(0, 30))
        self.progressBar_2.setProperty("value", 24)
        self.progressBar_2.setObjectName("progressBar_2")
        self.gridLayout.addWidget(self.progressBar_2, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 2)
        gameWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=gameWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        gameWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=gameWindow)
        self.statusbar.setObjectName("statusbar")
        gameWindow.setStatusBar(self.statusbar)

        self.retranslateUi(gameWindow)
        QtCore.QMetaObject.connectSlotsByName(gameWindow)

    def retranslateUi(self, gameWindow):
        _translate = QtCore.QCoreApplication.translate
        gameWindow.setWindowTitle(_translate("gameWindow", "MainWindow"))
        self.label.setText(_translate("gameWindow", "starting screen..."))
        self.pushButton_3.setText(_translate("gameWindow", "."))
        self.pushButton_2.setText(_translate("gameWindow", "PRESS TO START"))
        self.pushButton.setText(_translate("gameWindow", "."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    gameWindow = QtWidgets.QMainWindow()
    ui = Ui_gameWindow()
    ui.setupUi(gameWindow)
    gameWindow.show()
    sys.exit(app.exec())
