# Form implementation generated from reading ui file 'MiniCombatGui.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_gameWindow(object):
    def setupUi(self, gameWindow):
        gameWindow.setObjectName("gameWindow")
        gameWindow.resize(800, 600)
        gameWindow.setMinimumSize(QtCore.QSize(800, 600))
        gameWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(parent=gameWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 3, 781, 561))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.TextLabel = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.TextLabel.setMinimumSize(QtCore.QSize(0, 150))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.TextLabel.setFont(font)
        self.TextLabel.setObjectName("TextLabel")
        self.gridLayout.addWidget(self.TextLabel, 4, 0, 1, 2)
        self.playerGraphic = QtWidgets.QGraphicsView(parent=self.gridLayoutWidget)
        self.playerGraphic.setMinimumSize(QtCore.QSize(250, 250))
        self.playerGraphic.setMaximumSize(QtCore.QSize(250, 250))
        self.playerGraphic.setObjectName("playerGraphic")
        self.gridLayout.addWidget(self.playerGraphic, 1, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.EnemyGraphic = QtWidgets.QGraphicsView(parent=self.gridLayoutWidget)
        self.EnemyGraphic.setMinimumSize(QtCore.QSize(250, 250))
        self.EnemyGraphic.setMaximumSize(QtCore.QSize(250, 250))
        self.EnemyGraphic.setObjectName("EnemyGraphic")
        self.gridLayout.addWidget(self.EnemyGraphic, 1, 1, 1, 1, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.FirstButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.FirstButton.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.FirstButton.setFont(font)
        self.FirstButton.setObjectName("FirstButton")
        self.horizontalLayout.addWidget(self.FirstButton)
        self.SecindButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.SecindButton.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.SecindButton.setFont(font)
        self.SecindButton.setObjectName("SecindButton")
        self.horizontalLayout.addWidget(self.SecindButton)
        self.ThirdButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.ThirdButton.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.ThirdButton.setFont(font)
        self.ThirdButton.setObjectName("ThirdButton")
        self.horizontalLayout.addWidget(self.ThirdButton)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 0, 1, 2)
        self.PlayerHPbar = QtWidgets.QProgressBar(parent=self.gridLayoutWidget)
        self.PlayerHPbar.setMinimumSize(QtCore.QSize(0, 30))
        self.PlayerHPbar.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.PlayerHPbar.setProperty("value", 24)
        self.PlayerHPbar.setObjectName("PlayerHPbar")
        self.gridLayout.addWidget(self.PlayerHPbar, 0, 0, 1, 1)
        self.EnemyHPbar = QtWidgets.QProgressBar(parent=self.gridLayoutWidget)
        self.EnemyHPbar.setMinimumSize(QtCore.QSize(0, 30))
        self.EnemyHPbar.setProperty("value", 24)
        self.EnemyHPbar.setObjectName("EnemyHPbar")
        self.gridLayout.addWidget(self.EnemyHPbar, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 2)
        gameWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=gameWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        gameWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=gameWindow)
        self.statusbar.setObjectName("statusbar")
        gameWindow.setStatusBar(self.statusbar)

        self.retranslateUi(gameWindow)
        QtCore.QMetaObject.connectSlotsByName(gameWindow)

    def retranslateUi(self, gameWindow):
        _translate = QtCore.QCoreApplication.translate
        gameWindow.setWindowTitle(_translate("gameWindow", "MainWindow"))
        self.TextLabel.setText(_translate("gameWindow", "starting screen..."))
        self.FirstButton.setText(_translate("gameWindow", "."))
        self.SecindButton.setText(_translate("gameWindow", "PRESS TO START"))
        self.ThirdButton.setText(_translate("gameWindow", "."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    gameWindow = QtWidgets.QMainWindow()
    ui = Ui_gameWindow()
    ui.setupUi(gameWindow)
    gameWindow.show()
    sys.exit(app.exec())
